Bootstrap: docker
From: quay.io/biocontainers/prodigal:2.6.3--h516909a_2

%labels
    MAINTAINER icaoberg
    EMAIL icaoberg@psc.edu
    SUPPORT help@psc.edu
    REPOSITORY https://github.com/pscedu/singularity-prodigal
    COPYRIGHT Copyright © 2021-2025 Pittsburgh Supercomputing Center. All Rights Reserved.
    VERSION 2.6.3

%runscript
    prodigal "$@"